version: "3"

services:
  treasurenetdnode0:
    container_name: treasurenetdnode0
    image: "treasurenet/node:1.0"
    ports:
      - "26657:26657"
      - "8545:8545"
      - "8546:8546"
      - "8125:8125"
    environment:
      - ID=0
      - LOG=${LOG:-treasurenetd.log}
    volumes:
      - ./localnet-setup/node0/treasurenetd:/treasurenet:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  treasurenetdnode1:
    container_name: treasurenetdnode1
    image: "treasurenetd/node"
    ports:
      - "26658:26657"
      - "8555:8545"
      - "8556:8546"
      - "8126:8125"
    environment:
      - ID=1
      - LOG=${LOG:-treasurenetd.log}
    volumes:
      - ./localnet-setup/node1/treasurenetd:/treasurenet:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  treasurenetdnode2:
    container_name: treasurenetdnode2
    image: "treasurenetd/node"
    environment:
      - ID=2
      - LOG=${LOG:-treasurenetd.log}
    ports:
      - "26659:26657"
      - "8565:8545"
      - "8566:8546"
      - "8127:8125"
    volumes:
      - ./localnet-setup/node2/treasurenetd:/treasurenet:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  treasurenetdnode3:
    container_name: treasurenetdnode3
    image: "treasurenetd/node"
    environment:
      - ID=3
      - LOG=${LOG:-treasurenetd.log}
    ports:
      - "26660:26657"
      - "8575:8545"
      - "8576:8546"
      - "8128:8125"
    volumes:
      - ./localnet-setup/node3/treasurenetd:/treasurenet:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

networks:
  localnet:
