---
- name: Deploy Node
  hosts: all
  become: yes

  vars:
    PATH: /home/ubuntu
    GRAFANA_PORT: 3043
    PROMETHEUS_PORT: 3041
    NODEEXPLORTER_PORT: 3045
    LOKI_PORT: 3046
    USER: ubuntu
    nodes:
      - id: "node1"
        node_number: 1
      - id: "node2"
        node_number: 2
      - id: "node3"
        node_number: 3
      - id: "node4"
        node_number: 4
      - id: "seednode"
        node_number: 5

  tasks:

    - name: Print current working directory and list files
      shell: |
        pwd
        ls
        sudo rm -rf {{ PATH }}/docker/*
        sudo rm -rf {{ PATH }}/.treasurenetd
      register: shell_output
      ignore_errors: yes
      # Print current working directory and list files

    - name: Display shell output
      debug:
        var: shell_output.stdout_lines
      # Display shell output

    - name: Create directory for docker configuration
      file:
        path: "{{ PATH }}/docker"
        state: directory
        owner: "{{ USER }}"
        group: "{{ USER }}"
        mode: '0755'
      # Create directory for docker configuration

    - name: Create nginx directory 
      file:
        path: "/data/nginx"
        state: directory
        owner: "{{ USER }}"
        group: "{{ USER }}"
        mode: '0755'

    - name: Copy Docker config files to server
      copy:
        src: docker/
        dest: "{{ PATH }}/docker"
        force: yes
        owner: "{{ USER }}"
        group: "{{ USER }}"
      # Copy Docker config files to server

    - name: Copy treasurenetd binary to EC2 instance
      copy:
        src: docker/treasurenetd
        dest: "/usr/bin/treasurenetd"
        force: yes
        owner: "{{ USER }}"
        group: "{{ USER }}"
        mode: '0755'
      # Copy treasurenetd binary to EC2 instance

    - name: Perform initial setup checks
      shell: |
        source /etc/profile
        chmod +x /usr/bin/treasurenetd
        chmod +x {{ PATH }}/docker/docker-compose.yaml
        ls $(go env GOPATH)/bin
        mkdir -p "{{ PATH }}/.treasurenetd"
      args:
        executable: /bin/bash
      # Perform initial setup checks

    - name: Copy tn data files to server
      copy:
        src: "/data/{{ item.id }}/.treasurenetd/"
        dest: "{{ PATH }}/.treasurenetd/"
        force: yes
        owner: "{{ USER }}"
        group: "{{ USER }}"
      loop: "{{ nodes }}"
      loop_control:
        loop_var: item
      when: node_id == item.id
      # Copy tn nodes' data files to server

    - name: Copy nginx data files to server
      copy:
        src: "/data/nginx/{{ item.id }}/*"
        dest: "/data/nginx/"
        force: yes
        owner: "{{ USER }}"
        group: "{{ USER }}"
      loop: "{{ nodes }}"
      loop_control:
        loop_var: item
      when: node_id == item.id
      # Copy tn nodes' data files to server

    - name: Add number={{ item.node_number }} to .env file
      lineinfile:
        path: "{{ PATH }}/docker/.env"
        regexp: '^number='
        line: "number={{ item.node_number }}"
        state: present
      loop: "{{ nodes }}"
      loop_control:
        loop_var: item
      when: node_id == item.id
      # Add number to .env file




    - name: Ensure .env file ownership and permissions
      file:
        path: "{{ PATH }}/docker/.env"
        owner: "{{ USER }}"
        group: "{{ USER }}"
        mode: '0644'
      loop: "{{ nodes }}"
      loop_control:
        loop_var: item
      when: node_id == item.id
      # Ensure .env file ownership and permissions

    - name: Convert ip_mapping.json to .env
      shell: |
        jq -r 'to_entries[] | "\(.key)_ip=\(.value.private_ip)"' ip_mapping.json >> .env
      args:
        chdir: "{{ PATH }}/docker"
      when: node_id in ['node1', 'node2', 'node3', 'node4', 'seednode']

      # Convert ip_mapping.json to .env

    - name: Display .env file
      shell: cat .env
      args:
        chdir: "{{ PATH }}/docker"

      # Display .env file
    - name: Add persistent_peers for node={{ item.node_number }} to .env file (number == 1)
      lineinfile:
        path: "{{ PATH }}/docker/.env"
        regexp: '^PERSISTENT_PEERS_OPTION'
        line: "PERSISTENT_PEERS_OPTION="
        state: present
      loop: "{{ nodes }}"
      loop_control:
        loop_var: item
      when: node_id == item.id and item.node_number == 1
      # Add empty PERSISTENT_PEERS_OPTION for node number 1

    - name: Get node address from .env
      shell: "grep -oP '^node{{ (item.node_number - 1) }}_address=\\K.*' {{ PATH }}/docker/.env"
      register: node_address
      loop: "{{ nodes }}"
      loop_control:
        loop_var: item
      when: node_id == item.id and item.node_number != 1

    - name: Get node IP from .env
      shell: "grep -oP '^node{{ (item.node_number - 1) }}_ip=\\K.*' {{ PATH }}/docker/.env"
      register: node_ip
      loop: "{{ nodes }}"
      loop_control:
        loop_var: item
      when: node_id == item.id and item.node_number != 1

    - name: Debug node_address
      debug:
        msg: |
          node_address.results: {{ node_address.results | to_nice_json }}
          current item.id: {{ item.id }}
      loop: "{{ nodes }}"
      loop_control:
        loop_var: item
      when: node_id == item.id and item.node_number != 1

    - name: Debug node_ip
      debug:
        msg: |
          node_ip.results: {{ node_ip.results | to_nice_json }}
          current item.id: {{ item.id }}
      loop: "{{ nodes }}"
      loop_control:
        loop_var: item
      when: node_id == item.id and item.node_number != 1

    - name: Add persistent_peers for node={{ item.node_number }} to .env file (other than 1)
      lineinfile:
        path: "{{ PATH }}/docker/.env"
        regexp: '^PERSISTENT_PEERS_OPTION'
        line: "PERSISTENT_PEERS_OPTION=--p2p.persistent_peers={{ (node_address.results | selectattr('item.id', 'equalto', item.id) | first).stdout }}@{{ (node_ip.results | selectattr('item.id', 'equalto', item.id) | first).stdout }}:26656"
        state: present
      loop: "{{ nodes }}"
      loop_control:
        loop_var: item
      when: node_id == item.id and item.node_number != 1

    - name: Modify docker-compose.yaml for seed node (node_number == 5)
      shell: |
        if [ "{{ item.node_number }}" -eq 5 ]; then
          # Update container_name to "treasurenet-seednode"
          sed -i 's/container_name: treasurenet-node${number}/container_name: treasurenet-seednode/' {{ PATH }}/docker/docker-compose.yaml

          # Update command to seed node configuration
          sed -i '/command:/,/^\s*$/s|treasurenetd start --chain-id treasurenet_5005-1 --evm.tracer=json --json-rpc.api eth,txpool,net,web3,miner,debug --pruning=nothing --trace --json-rpc.address 0.0.0.0:8555 --rpc.laddr tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants|treasurenetd start --chain-id treasurenet_5005-1 --p2p.seed_mode=true --p2p.pex=true |' {{ PATH }}/docker/docker-compose.yaml
        fi
      loop: "{{ nodes }}"
      loop_control:
        loop_var: item
      when: node_id == item.id and item.node_number == 5
      # Modify docker-compose.yaml for seed node (node_number == 5)




    - name: Change hosts
      shell: |
        chmod +x update_hosts.sh
        bash ./update_hosts.sh
        cat /etc/hosts
      args:
        chdir: "{{ PATH }}/docker"
      # Change hosts

    - name: Docker-compose up
      shell: |
        source .env
        export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        export AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
        aws ecr get-login-password --region $inputs_ecr_repo_aws_region | docker login --username AWS --password-stdin $secrets_ECR_REGISTRY
        docker-compose down
        docker-compose pull
        docker-compose up -d
      args:
        chdir: "{{ PATH }}/docker"
        executable: /bin/bash
      # Docker-compose up


    - name: Docker-compose nginx up
      shell: |
        source .env
        export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        export AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
        aws ecr get-login-password --region $inputs_ecr_repo_aws_region | docker login --username AWS --password-stdin $secrets_ECR_REGISTRY
        docker-compose -f nginx.yaml down
        docker-compose -f nginx.yaml pull
        docker-compose -f nginx.yaml up -d
      args:
        chdir: "{{ PATH }}/docker"
        executable: /bin/bash
      # Docker-compose up
