version: "3.8"

networks:
  treasurenet-test:

services:
  treasurenetdnode:
    container_name: treasurenet-node${number}
    image: ${IMAGE_NAME}
    command: >
      treasurenetd start --chain-id treasurenet_5005-1 --evm.tracer=json --json-rpc.api eth,txpool,net,web3,miner,debug --pruning=nothing --trace --json-rpc.address 0.0.0.0:8555 --rpc.laddr tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants
      ${PERSISTENT_PEERS_OPTION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - /home/ubuntu/.treasurenetd:/root/.treasurenetd
    ports:
      - "26656:26656"
      - "26657:26657"
      - "26660:26660"
      - "8555:8555"
      - "8546:8546"
      - "8125:8125"
      - "9090:9090"
      - "1317:1317"
    networks:
      - treasurenet-test
