name: CI
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}-build
  cancel-in-progress: true

jobs:
  
  check-unwanted-characters:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Check for Unwanted Characters
      run: |
        if grep -rHnP --exclude-dir='.git' --exclude='*.wasm' --exclude='*.png' --exclude='*.jpg' "[\x{4e00}-\x{9fff}]" . ; then
          echo "Unwanted characters found!"
          exit 1
        else
          echo "All good."
        fi

  golangci:
    needs: [check-unwanted-characters]
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          check-latest: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        continue-on-error: true
        with:
          version: v1.54
          args: --out-format=tab --timeout=10m

  unit-tests:
    needs: [golangci]
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.19'
          check-latest: false

      - name: Run Unit Tests
        run: |
          make test

  build:
    runs-on: ubuntu-latest
    needs: [unit-tests]
    strategy:
      matrix:
        go-arch: ["amd64"]
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          check-latest: true

        ###################
        #### Build App ####
        ###################
      - name: Build
        run: GOARCH=${{ matrix.go-arch }} make build
