name: TN Incremental Secret Scan

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  secret-scan:
    uses: treasurenetprotocol/reusable-workflows/.github/workflows/reusable-secrets-scanning.yml@d82d3ef57336183b47a09c40717ea0560e4e50f6
    with:
      scan_mode: ${{ github.event_name == 'pull_request' && 'pr' || 'push' }}
      fetch_depth: 0
      fail_threshold: high
      config_ref: d82d3ef57336183b47a09c40717ea0560e4e50f6
